*** Makefile.org	2007-10-13 01:43:44.000000000 +0900
--- Makefile	2007-11-21 14:24:41.000000000 +0900
***************
*** 9,14 ****
--- 9,16 ----
  
  obj-y	 += mem.o random.o tty_io.o n_tty.o tty_ioctl.o
  
+ obj-$(CONFIG_HELLO)		+= hello/
+ 
  obj-$(CONFIG_LEGACY_PTYS)	+= pty.o
  obj-$(CONFIG_UNIX98_PTYS)	+= pty.o
  obj-y				+= misc.o
